darkwear/urls.py
from django.conf import settings 
from django.urls import path,include
from django.contrib import admin 
from django.conf.urls.static import static
urlpatterns = [
    path('adminww/', admin.site.urls),
    path('',include("home.urls")),
    path('user/',include("user.urls")),
    path('seller/',include("seller.urls")),
    path('admin/',include("dw_admin.urls")),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name='homepage'
urlpatterns = [
    path('',views.home_homepage,name = 'home'),
    path('seller_login',views.seller_login,name = 'seller_login'),
    path('seller_registration',views.seller_registration,name = 'seller_registration'),
    path('login',views.home_login,name = 'login'),
    path('register',views.home_register,name = 'register'),
    path('jacket',views.home_jacket,name = 'jacket'),
    path('hoodie',views.home_hoodie,name = 'hoodie'),
    path('sweater',views.home_sweater,name = 'sweater'),
    path('t-shirt',views.home_tshirt,name = 't-shirt'),
    path('pants',views.home_pant,name = 'pants'),
    path('hats',views.home_hats,name = 'hats'),
    path('jewelery',views.home_jewelery,name = 'jewelery'),
    path('accessories',views.home_accessories,name = 'accessories'),
    path('product_details',views.product_details,name = 'product_details')

]

user/urls.py
from django.urls import path
from . import views
app_name='user'
urlpatterns = [
    path('',views.user,name='home'),
    path('jacket',views.user_jacket,name = 'jacket'),
    path('hoodie',views.user_hoodie,name = 'hoodie'),
    path('sweater',views.user_sweater,name = 'sweater'),
    path('t-shirt',views.user_tshirt,name = 't-shirt'),
    path('pants',views.user_pant,name = 'pants'),
    path('hats',views.user_hats,name = 'hats'),
    path('accessories',views.user_accessories,name = 'accessories'),
    path('product_details/<int:p_id>',views.user_product_details,name = 'product_details'),
    path('get_quantity/',views.get_quantity, name='get_quantity'),
    # path('profile',views.profile,name = 'profile'),
    path('personal_details',views.personal_details, name = 'personal_details'),
    path('edit_personal_details',views.edit_personal_details,name = 'edit_personal_details'),
    path('manage_address',views.manage_address, name = 'manage_address'),
    path('edit_manage_address',views.edit_manage_address, name = 'edit_manage_address'),
    path('coupon',views.my_coupons, name = 'coupon'),
    path('my_reviews',views.my_reviews,name = 'my_reviews'),
    path('cart',views.user_cart,name = 'cart'),
    path('update_cart/', views.update_cart, name='update_cart'),
    path('delete_from_cart/', views.delete_from_cart, name='delete_from_cart'),
    # path('checkout',views.checkout, name = 'checkout'),
    path('pdf',views.generate_pdf, name = 'pdf'),
    
]

user/models.py
from django.db import models
from home.models import *
from seller.models import *
# Create your models here.
class Cart(models.Model):
    customer = models.ForeignKey(Customer,on_delete=models.CASCADE)   
    product = models.ForeignKey(Products,on_delete=models.CASCADE)   
    variant = models.ForeignKey(Variant,on_delete=models.CASCADE)
    qty = models.IntegerField()

home/views.py
from django.shortcuts import render,redirect
from home.models import Customer
from home.models import Seller
from django.contrib import messages
from django.shortcuts import render 
from django.http import HttpResponse 
import logging
from random import randint
from django.conf import settings
from django.core.mail import send_mail


# Create your views here.
def home_homepage(request):
    return render(request,'home_templates/user_index.html')
    

def home_login(request):
    msg="" 
    if request.method == 'POST':
        u_email = request.POST['email']  
        u_password = request.POST['password']
        try:
            customerlog = Customer.objects.get(
                email= u_email,
                password= u_password
            )
            request.session['customer'] = customerlog.id
            return redirect('user:home')
        except:
              msg="Invalid Username or password"  
            #   return redirect('common:user_form') 
    return render(request,'home_templates/login1.html',{'message':msg}) 

def home_register(request):
    if request.method == 'POST':
        print('test')
        u_name = request.POST['name']
        u_gender = request.POST['gender']
        u_phone = request.POST['phone']
        u_dob = request.POST['dob']
        u_house = request.POST['house']
        u_street = request.POST['street']
        u_city = request.POST['city']
        u_pincode = request.POST['pincode']
        u_email = request.POST['email']
        u_password = request.POST['password']
        u_customer = Customer(
            name= u_name,
            gender= u_gender,
            phone= u_phone,
            dob= u_dob,
            house= u_house,
            street= u_street,
            city= u_city,
            pincode= u_pincode,
            email= u_email,
            password= u_password
        )
        u_customer.save()  
        messages.success( request,'Successfully Registered')
        return redirect('homepage:login')
    return render(request,'home_templates/register.html')

def seller_login(request):
    msg="" 
    if request.method == 'POST':
        s_username= request.POST['username']  
        s_password = request.POST['password']
        try:
            sellerlog = Seller.objects.get(username= s_username,password= s_password)
            request.session['seller'] = sellerlog.id
            return redirect('seller:shome')
        except:
            msg="Invalid Username or password"  
            #return redirect('common:user_form') 
    return render(request,'home_templates/seller_login.html',{'message':msg})

def seller_registration(request):
     if request.method == 'POST':
        s_name = request.POST['name']
        s_username = request.POST['username']
        s_email = request.POST['email']
        s_phone = request.POST['phone']
        s_account = request.POST['account']
        s_ifsc = request.POST['ifsc']
        s_adddress = request.POST['address']
        s_sellerpic = request.FILES['sellerpic']
        s_password = str(s_username)+'-'+s_phone[6-10]
        s_seller = Seller(
            name= s_name,
            username=s_username,
            email= s_email,
            phone= s_phone,
            address= s_adddress,
            account=s_account,
            ifsc= s_ifsc,
            password= s_password,
            sellerpic= s_sellerpic  
        )
        s_seller.save()     
        messages.success( request,'Successfully Registered')
        email_subject='DarkWear Seller Account Registration'
        email_content='Dear team '+str(s_username)+'\n Thank You for registering your buisness with our website.\nWe ar eager to do buisness with you and grow our business higher together.\nYour password for login is\n password:'+s_password
         
        send_mail(
                  email_subject,
                  email_content, 
                  settings.EMAIL_HOST_USER,
                  [s_email,])
        return redirect('homepage:seller_login')
     return render(request,'home_templates/seller_registration.html')

def home_jacket(request):
    return render(request,'home_templates/jacket.html')

def home_hoodie(request):
    return render(request,'home_templates/hoodie.html')

def home_sweater(request):
    return render(request,'home_templates/sweaters.html')

def home_tshirt(request):
    return render(request,'home_templates/t-shirt.html')

def home_pant(request):
    return render(request,'home_templates/pants.html')

def home_hats(request):
    return render(request,'home_templates/hats.html')                 

def home_accessories(request):
    return render(request,'home_templates/accessories.html')

def home_jewelery(request):
    return render(request,'home_templates/jewelery.html')                   

def product_details(request):
    return render(request,'user_templates/product_details.html')

user/views.py
from django.shortcuts import render,redirect
from home.models import *
from seller.models import *
from user.models import *
from home.models import *
import pprint
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
from django.template.loader import render_to_string
from django.contrib import messages
from django.template.loader import get_template
from xhtml2pdf import pisa
from .models import Cart



# Create your views here.
# def profile(request):
#     return render(request,'user_templates/profile.html',{'customer':customer})

def personal_details(request):
    customer = Customer.objects.get(id = request.session['customer'])
    return render(request,'user_templates/profile-personal-details.html',{'customer':customer})

def edit_personal_details(request):
    customer = Customer.objects.get(id=request.session['customer'])
    if request.method == 'POST':
        customer.name = request.POST['name']
        customer.email = request.POST['email']
        customer.phone = request.POST['phone']
        customer.dob = request.POST['dob']
        customer.save()
        return redirect('user:personal_details')
    return render(request,'user_templates/profile-edit-personal-details.html',{'customer':customer})

def manage_address(request):
    customer = Customer.objects.get(id = request.session['customer'])
    return render(request,'user_templates/profile-manage-address.html',{'customer':customer})

def edit_manage_address(request):
    customer = Customer.objects.get(id=request.session['customer'])
    if request.method == 'POST':
        customer.house = request.POST['house']
        customer.street = request.POST['street']
        customer.city = request.POST['city']
        customer.pincode = request.POST['pincode']
        customer.save()
        return redirect('user:manage_address')
    return render(request,'user_templates/profile-edit-manage-address.html',{'customer':customer})

def my_coupons(request):
    customer = Customer.objects.get(id = request.session['customer'])
    return render(request,'user_templates/profile-coupon.html',{'customer':customer})

def my_reviews(request):
    customer = Customer.objects.get(id = request.session['customer'])
    return render(request,'user_templates/profile-my-reviews.html',{'customer':customer})

def user(request):
    customer_details = Customer.objects.get(id = request.session['customer'])
    return render(request,'user_templates/user_index.html')

def user_jacket(request):
    category = Category.objects.get(category_name = 'jacket')
    jacket = Products.objects.filter(category_id = category,status = 'approved')
    
    pprint.pprint(jacket)
    return render(request,'user_templates/jacket.html',{'jackets':jacket})


def user_hoodie(request):
    category = Category.objects.get(category_name = 'hoodie')
    hoodie = Products.objects.filter(category_id = category,status = 'approved')
    return render(request,'user_templates/hoodie.html',{'hoodies':hoodie})

def user_sweater(request):
    category = Category.objects.get(category_name = 'sweatshirt')
    sweater = Products.objects.filter(category_id = category,status = 'approved')
    return render(request,'user_templates/sweaters.html',{'sweaters':sweater})

def user_tshirt(request):
    category = Category.objects.get(category_name = 't-shirt')
    tshirt = Products.objects.filter(category_id = category,status = 'approved')
    return render(request,'user_templates/t-shirt.html',{'tshirts':tshirt})

def user_pant(request):
    category = Category.objects.get(category_name = 'pant')
    pant = Products.objects.filter(category_id = category,status = 'approved')
    return render(request,'user_templates/pants.html',{'pants':pant})

def user_hats(request):
    category = Category.objects.get(category_name = 'hat')
    hat = Products.objects.filter(category_id = category,status = 'approved')
    return render(request,'user_templates/hats.html',{'hats':hat})                 

def user_accessories(request):
    category = Category.objects.get(category_name = 'accessories')
    accessory = Products.objects.filter(category_id = category,status = 'approved')
    return render(request,'user_templates/accessories.html',{'accessories':accessory}) 

def user_product_details(request, p_id):
    print(request)
    msg="" 
    product = Products.objects.get(id = p_id)
    variants = Variant.objects.filter(product_id = p_id)
    print(variants)
    album = Album.objects.filter(product_id = p_id)
    
    show_fit_type = True
    show_size_guide = True
    if product.category_id.category_name in ['accessories', 'hat']:
        show_fit_type = False
        try:
            context = {
                'product': product,
                'variants': variants,
                'albums': album,
                'show_fit_type': show_fit_type,
                'show_size_guide': show_size_guide,
                'size_guide': product.size_guide.url
            }
        except ValueError:
            show_size_guide = False
            context = {
                'product': product,
                'variants': variants,
                'albums': album,
                'show_fit_type': show_fit_type,
                'show_size_guide': show_size_guide,
                'size_guide': None  # default value for size_guide
            }

    else:
        context = {
            'product': product,
            'variants': variants,
            'albums': album,
            'show_fit_type': show_fit_type,
            'show_size_guide': show_size_guide,
            'size_guide': product.size_guide.url
        }
        
    if request.method == 'POST':
        u_id=request.session.get('customer')
        quantity = request.POST.get('quantity')
        # v_id = request.POST.get('variant_id')
        # print(v_id)
        size = request.POST.get('size')
        size_id = size_id = int(size.split()[2].strip("()"))
        print(size_id)
        variants = Variant.objects.get(product_id = product,size_id=size_id)
        print(variants)
        item = Cart.objects.filter(customer_id =u_id ,product_id = p_id,variant_id=variants.id).exists()
        print(item)
        if not item:           #same as if item == false:
            cart= Cart(customer_id =u_id,product_id = p_id,variant_id=variants.id,qty = quantity)
            cart.save()
            return redirect('user:cart')

        else:
            print('already in cart')
            msg = 'Item already in cart'
            
        
    return render(request,'user_templates/product_details.html',context)

def get_quantity(request):
    print(request)
    if request.method == 'GET':
        product_id = request.GET.get('product_id')
        size_id = request.GET.get('size_id')
        print(size_id)
        print(product_id,size_id)
    variant = Variant.objects.get(product_id=product_id, size_id=size_id)
    available_quantity = variant.quantity

    data = {
        'available_quantity': available_quantity,
    }

    return JsonResponse(data)


    

def user_cart(request):
    if request.method == 'POST':
        return redirect('user:pdf') 
    cart = Cart.objects.filter(customer_id=request.session['customer'])
    product_id=Products.objects.all()     
    return render(request,'user_templates/cart.html',{'items':cart})

def update_cart(request):
    if request.method == 'POST':
        cart_item_id = request.POST.get('cart_item_id')
        quantity = request.POST.get('quantity')
        cart_item = Cart.objects.get(id=cart_item_id)
        cart_item.qty = quantity
        cart_item.save()
        cart = Cart.objects.filter(customer_id=request.session['customer'])
        cart_html = render_to_string('cart.html', {'items': cart})
        messages.success(request, "Cart updated successfully")
        return HttpResponse(cart_html)
    else:
        return redirect('cart')

@csrf_exempt
def delete_from_cart(request):
    if request.method == 'POST':
        cart_item_id = request.POST.get('cart_item_id')
        try:
            cart_item = Cart.objects.get(id=cart_item_id)
            cart_item.delete()
            return JsonResponse({'success': True})
        except Cart.DoesNotExist:
            return JsonResponse({'success': False, 'error': 'Cart item does not exist.'})
    else:
         return JsonResponse({'success': False, 'error': 'Invalid request method.'})
     

# def checkout(request):
#     customer = Customer.objects.get(id = request.session['customer'])
#     items = Cart.objects.filter(customer_id=request.session['customer'])
#     grand_total = 0
#     for item in items:
#         grand_total += item.product.price * item.qty
    
#     context = {
#         'items': items,
#         'grand_total': grand_total,
#         'customers' : customer,
#     }
    
#     return render(request, 'user_templates/checkout.html', context)

def generate_pdf(request):
    customer = Customer.objects.get(id = request.session['customer'])
    items = Cart.objects.filter(customer_id=request.session['customer'])
    grand_total = 0
    for item in items:
        grand_total += item.product.price * item.qty
    
    context = {
        'items': items,
        'grand_total': grand_total,
        'customers' : customer,
    }
    
    template_path = 'user_templates/checkout.html'
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="checkout.pdf"'
    
    template = get_template(template_path)
    html = template.render(context)
    
    pisa_status = pisa.CreatePDF(html, dest=response)
    
    if pisa_status.err:
        return HttpResponse('An error occurred while generating the PDF')
    
    return response     
     

user/templates/user_templates/hats.html
{% extends 'user_templates/user_master.html' %} {% load static %} {% block content %}
<link rel="stylesheet" href="{% static '/css/styleha.css' %}" as="style">
<script src="{% static 'js/tinysort.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <!-----------------------------------------------------main1---------------------------------------------------------->
  <div id="parallax-world-of-ugg">
    <section>
        <div class="parallax-one">
          <!-- <p class="p11">Your Exclusive store for</p> -->
          <h2 style="font-family: impact;">HATS</h2>
      </div>
    </section>
    
    <section class="pad">
      <div class="container">
        <div class="row justify-content-between">
          <div class="col-lg-2 col-md-2 col-sm-4 justify-content-start text-start">
            <h4 id="newarrival">page 1 of 1</h4>
          </div>
          <div class="col-lg-4 col-md-4 col-sm-4 justify-content-end text-end">
            <label class="newarrival"><b>Sort by</b></label>
            <select name="sort" id="sort-by" onchange="sortProducts()">
              <option disabled selected>--sort--</option>
              <option value="pl">price(lowest first)</option>
              <option value="ph">price(highest first)</option>
            </select>
          </div>
        </div>
        <br><br>
        <div class="row justify-content-start">
          {% for hat in hats %}
          <div class="col-lg-3 col-md-6 col-sm-6 justify-content-center">
            <div id="product-grid">
              <div id="product-image">
                <a href="{% url 'user:product_details' hat.id %}" id="image">
                  <img src="{{hat.thumbnail.url}}">
                </a>
                <span id="product-discount-label">-23%</span>
                <a href="" id="add-to-cart">Add to Cart</a>
              </div>
              <div id="product-content">
                <div id="title" style="height: 32px; cursor:pointer"><p>{{hat.product_name}}</p></div>
                <div class="price"><b>${{hat.price}}</b></div>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
      <div id="product-list"></div>
  
    </section>
  
  </div>
  
  <script>
    function sortProducts() {
      // Get the sort value selected by the user
      var sortValue = $('#sort-by').val();
      
      // Use TinySort to sort the products based on their price
      tinysort('#product-grid', { 
        selector: '.price', 
        order: sortValue === 'pl' ? 'asc' : 'desc' 
      });
    }
  </script>

{% endblock %}

user/templates/user_templates/hoodie.html
{% extends 'user_templates/user_master.html' %} {% load static %} {% block content %}
<link rel="stylesheet" href="{% static '/css/styleho.css' %}" as="style">
<script src="{% static 'js/tinysort.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <!-----------------------------------------------------main1---------------------------------------------------------->
  <div id="parallax-world-of-ugg">
    <section>
        <div class="parallax-one">
          <!-- <p class="p11">Your Exclusive store for</p> -->
          <h2 style="font-family: impact;">HOODIESS</h2>
      </div>
    </section>
    
    <section class="pad">
      <div class="container">
        <div class="row justify-content-between">
          <div class="col-lg-2 col-md-2 col-sm-4 justify-content-start text-start">
            <h4 id="newarrival">page 1 of 1</h4>
          </div>
          <div class="col-lg-4 col-md-4 col-sm-4 justify-content-end text-end">
            <label class="newarrival"><b>Sort by</b></label>
            <select name="sort" id="sort-by" onchange="sortProducts()">
              <option disabled selected>--sort--</option>
              <option value="pl">price(lowest first)</option>
              <option value="ph">price(highest first)</option>
            </select>
          </div>
        </div>
        <br><br>
        <div class="row justify-content-start">
          {% for hoodie in hoodies %}
          <div class="col-lg-3 col-md-6 col-sm-6 justify-content-center">
            <div id="product-grid">
              <div id="product-image">
                <a href="{% url 'user:product_details' hoodie.id %}" id="image">
                  <img src="{{hoodie.thumbnail.url}}">
                </a>
                <span id="product-discount-label">-23%</span>
                <a href="" id="add-to-cart">Add to Cart</a>
              </div>
              <div id="product-content">
                <div id="title" style="height: 32px; cursor:pointer"><p>{{hoodie.product_name}}</p></div>
                <div class="price"><b>${{hoodie.price}}</b></div>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
      <div id="product-list"></div>
  
    </section>
  
  </div>
  
  <script>
    function sortProducts() {
      // Get the sort value selected by the user
      var sortValue = $('#sort-by').val();
      
      // Use TinySort to sort the products based on their price
      tinysort('#product-grid', { 
        selector: '.price', 
        order: sortValue === 'pl' ? 'asc' : 'desc' 
      });
    }
  </script>

{% endblock%}
 

user/templates/user_templates/jacket.html
{% extends 'user_templates/user_master.html' %} {% load static %} {% block content %}
<link rel="stylesheet" href="{% static '/css/stylej.css' %}" as="style">
<script src="{% static 'js/tinysort.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<!-----------------------------------------------------main1---------------------------------------------------------->
<div id="parallax-world-of-ugg">
  <section>
    <div class="parallax-one">
      <!-- <p class="p11">Your Exclusive store for</p> -->
      <h2 style="font-family: impact;">JACKETS</h2>
    </div>
  </section>

  <section class="pad">
    <div class="container">
      <div class="row justify-content-between">
        <div class="col-lg-2 col-md-2 col-sm-4 justify-content-start text-start">
          <h4 id="newarrival">page 1 of 1</h4>
        </div>
        <div class="col-lg-4 col-md-4 col-sm-4 justify-content-end text-end">
          <label class="newarrival"><b>Sort by</b></label>
          <select name="sort" id="sort-by" onchange="sortProducts()">
            <option disabled selected>--sort--</option>
            <option value="pl">price(lowest first)</option>
            <option value="ph">price(highest first)</option>
          </select>
        </div>
      </div>

      <br><br>

      <div class="row justify-content-start">
        {% for jacket in jackets %}
        <div class="col-lg-3 col-md-6 col-sm-6 justify-content-center">
          <div id="product-grid">
            <div id="product-image">
              <a href="{% url 'user:product_details' jacket.id %}" id="image">
                <img src="{{jacket.thumbnail.url}}">
              </a>
              <span id="product-discount-label">-23%</span>
              <a href="" id="add-to-cart">Add to Cart</a>
            </div>
            <div id="product-content">
              <div id="title" style="height: 32px; cursor:pointer"><p>{{jacket.product_name}}</p></div>
              <div class="price"><b>${{jacket.price}}</b></div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
    <div id="product-list"></div>

  </section>

</div>

<script>
  function sortProducts() {
    // Get the sort value selected by the user
    var sortValue = $('#sort-by').val();
    
    // Use TinySort to sort the products based on their price
    tinysort('#product-grid', { 
      selector: '.price', 
      order: sortValue === 'pl' ? 'asc' : 'desc' 
    });
  }
</script>



{% endblock%}

user/templates/user_templates/pants.html
{% extends 'user_templates/user_master.html' %} {% load static %} {% block content %}
<link rel="stylesheet" href="{% static '/css/stylepa.css' %}" as="style">
<script src="{% static 'js/tinysort.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <!-----------------------------------------------------main1---------------------------------------------------------->
  <div id="parallax-world-of-ugg">
    <section>
        <div class="parallax-one">
          <!-- <p class="p11">Your Exclusive store for</p> -->
          <h2 style="font-family: impact;">PANTS</h2>
      </div>
    </section>
    
    <section class="pad">
      <div class="container">
        <div class="row justify-content-between">
          <div class="col-lg-2 col-md-2 col-sm-4 justify-content-start text-start">
            <h4 id="newarrival">page 1 of 1</h4>
          </div>
          <div class="col-lg-4 col-md-4 col-sm-4 justify-content-end text-end">
            <label class="newarrival"><b>Sort by</b></label>
            <select name="sort" id="sort-by" onchange="sortProducts()">
              <option disabled selected>--sort--</option>
              <option value="pl">price(lowest first)</option>
              <option value="ph">price(highest first)</option>
            </select>
          </div>
        </div>
  
        <br><br>
  
        <div class="row justify-content-start">
          {% for pant in pants %}
          <div class="col-lg-3 col-md-6 col-sm-6 justify-content-center">
            <div id="product-grid">
              <div id="product-image">
                <a href="{% url 'user:product_details' pant.id %}" id="image">
                  <img src="{{pant.thumbnail.url}}">
                </a>
                <span id="product-discount-label">-23%</span>
                <a href="" id="add-to-cart">Add to Cart</a>
              </div>
              <div id="product-content">
                <div id="title" style="height: 32px; cursor:pointer"><p>{{pant.product_name}}</p></div>
                <div class="price"><b>${{pant.price}}</b></div>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
      <div id="product-list"></div>
  
    </section>
  
  </div>
  
  <script>
    function sortProducts() {
      // Get the sort value selected by the user
      var sortValue = $('#sort-by').val();
      
      // Use TinySort to sort the products based on their price
      tinysort('#product-grid', { 
        selector: '.price', 
        order: sortValue === 'pl' ? 'asc' : 'desc' 
      });
    }
  </script>
  
  
  
  {% endblock%}

user/templates/user_templates/profile-coupon.html
{% extends 'user_templates/profile.html' %}{% load static %}

{% block page_content %}
  <h3>Available Coupons</h3>
  <div class="page-body">
  aeage
  </div>
{% endblock %}

user/templates/user_templates/profile-personal-details.html
{% extends 'user_templates/profile.html' %}{% load static %}

{% block page_content %}
  <h3>
    Personal Details &nbsp;&nbsp;&nbsp;&nbsp;  
    <small><a href="{% url 'user:edit_personal_details' %}">
      <span class="material-symbols-outlined">edit</span>edit
    </a></small>
  </h3>
  <form method="post" action="">
    {% csrf_token %}
    <div class="p-2">
      <label>Name</label><br>
      <input class="form" type="text" value="{{customer.name}}" disabled>
    </div>
    <div class="p-2">
      <label>Email</label><br>
      <input type="text" value="{{customer.email}}" disabled>
    </div>
    <div class="p-2">
      <label>Phone</label><br>
      <input type="number" value="{{customer.phone}}" disabled>
    </div>
    <div class="p-2">
      <label>Date of Birth</label><br>
      <input type="text" value="{{customer.dob}}" disabled>
    </div>

  </form>
{% endblock %}