darkwear/urls.py
from django.conf import settings 
from django.urls import path,include
from django.contrib import admin 
from django.conf.urls.static import static
urlpatterns = [
    path('adminww/', admin.site.urls),
    path('',include("home.urls")),
    path('user/',include("user.urls")),
    path('seller/',include("seller.urls")),
    path('admin/',include("dw_admin.urls")),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name='homepage'
urlpatterns = [
    path('',views.home_homepage,name = 'home'),
    path('seller_login',views.seller_login,name = 'seller_login'),
    path('seller_registration',views.seller_registration,name = 'seller_registration'),
    path('login',views.home_login,name = 'login'),
    path('register',views.home_register,name = 'register'),
    path('jacket',views.home_jacket,name = 'jacket'),
    path('hoodie',views.home_hoodie,name = 'hoodie'),
    path('sweater',views.home_sweater,name = 'sweater'),
    path('t-shirt',views.home_tshirt,name = 't-shirt'),
    path('pants',views.home_pant,name = 'pants'),
    path('hats',views.home_hats,name = 'hats'),
    path('jewelery',views.home_jewelery,name = 'jewelery'),
    path('accessories',views.home_accessories,name = 'accessories'),
    path('product_details',views.product_details,name = 'product_details')

]

home/models.py
from django.db import models
from unittest.util import _MAX_LENGTH


# Create your models here.
class Customer(models.Model):
    name = models.CharField(max_length=50)
    gender= models.CharField(max_length=10)
    phone = models.BigIntegerField()
    dob = models.CharField(max_length=70)
    house = models.CharField(max_length=100)
    street = models.CharField(max_length=100)
    city = models.CharField(max_length=50)
    pincode = models.IntegerField()
    email = models.CharField(max_length=50)
    password = models.CharField(max_length=20)
    
class Seller (models. Model):
    name = models.CharField (max_length=40) 
    username = models. CharField(max_length=60)
    email  = models. CharField (max_length=40) 
    password = models. CharField(max_length=30) 
    account = models.BigIntegerField()
    phone = models.BigIntegerField()
    ifsc = models. BigIntegerField()
    address = models.CharField(max_length=200) 
    sellerpic = models. ImageField(upload_to='seller/')    
    status = models.CharField(max_length=20,default='pending')

home/views.py
from django.shortcuts import render,redirect
from home.models import Customer
from home.models import Seller
from django.contrib import messages
from django.shortcuts import render 
from django.http import HttpResponse 
import logging
from random import randint
from django.conf import settings
from django.core.mail import send_mail


# Create your views here.
def home_homepage(request):
    return render(request,'home_templates/user_index.html')
    

def home_login(request):
    msg="" 
    if request.method == 'POST':
        u_email = request.POST['email']  
        u_password = request.POST['password']
        try:
            customerlog = Customer.objects.get(
                email= u_email,
                password= u_password
            )
            request.session['customer'] = customerlog.id
            return redirect('user:home')
        except:
              msg="Invalid Username or password"  
            #   return redirect('common:user_form') 
    return render(request,'home_templates/login1.html',{'message':msg}) 

def home_register(request):
    if request.method == 'POST':
        print('test')
        u_name = request.POST['name']
        u_gender = request.POST['gender']
        u_phone = request.POST['phone']
        u_dob = request.POST['dob']
        u_house = request.POST['house']
        u_street = request.POST['street']
        u_city = request.POST['city']
        u_pincode = request.POST['pincode']
        u_email = request.POST['email']
        u_password = request.POST['password']
        u_customer = Customer(
            name= u_name,
            gender= u_gender,
            phone= u_phone,
            dob= u_dob,
            house= u_house,
            street= u_street,
            city= u_city,
            pincode= u_pincode,
            email= u_email,
            password= u_password
        )
        u_customer.save()  
        messages.success( request,'Successfully Registered')
        return redirect('homepage:login')
    return render(request,'home_templates/register.html')

def seller_login(request):
    msg="" 
    if request.method == 'POST':
        s_username= request.POST['username']  
        s_password = request.POST['password']
        try:
            sellerlog = Seller.objects.get(username= s_username,password= s_password)
            request.session['seller'] = sellerlog.id
            return redirect('seller:shome')
        except:
            msg="Invalid Username or password"  
            #return redirect('common:user_form') 
    return render(request,'home_templates/seller_login.html',{'message':msg})

def seller_registration(request):
     if request.method == 'POST':
        s_name = request.POST['name']
        s_username = request.POST['username']
        s_email = request.POST['email']
        s_phone = request.POST['phone']
        s_account = request.POST['account']
        s_ifsc = request.POST['ifsc']
        s_adddress = request.POST['address']
        s_sellerpic = request.FILES['sellerpic']
        s_password = str(s_username)+'-'+s_phone[6-10]
        s_seller = Seller(
            name= s_name,
            username=s_username,
            email= s_email,
            phone= s_phone,
            address= s_adddress,
            account=s_account,
            ifsc= s_ifsc,
            password= s_password,
            sellerpic= s_sellerpic  
        )
        s_seller.save()     
        messages.success( request,'Successfully Registered')
        email_subject='DarkWear Seller Account Registration'
        email_content='Dear team '+str(s_username)+'\n Thank You for registering your buisness with our website.\nWe ar eager to do buisness with you and grow our business higher together.\nYour password for login is\n password:'+s_password
         
        send_mail(
                  email_subject,
                  email_content, 
                  settings.EMAIL_HOST_USER,
                  [s_email,])
        return redirect('homepage:seller_login')
     return render(request,'home_templates/seller_registration.html')

def home_jacket(request):
    return render(request,'home_templates/jacket.html')

def home_hoodie(request):
    return render(request,'home_templates/hoodie.html')

def home_sweater(request):
    return render(request,'home_templates/sweaters.html')

def home_tshirt(request):
    return render(request,'home_templates/t-shirt.html')

def home_pant(request):
    return render(request,'home_templates/pants.html')

def home_hats(request):
    return render(request,'home_templates/hats.html')                 

def home_accessories(request):
    return render(request,'home_templates/accessories.html')

def home_jewelery(request):
    return render(request,'home_templates/jewelery.html')                   

def product_details(request):
    return render(request,'user_templates/product_details.html')

home/templates/home_templates/login1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- css  -->
  <link rel="stylesheet" href="{% static '/css/stylelo.css' %}" as="style">

  <!---------------------------material icons------------------------------------------------->
  <link rel="stylesheet"
    href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,700,0,200" />
  <link rel="stylesheet"
    href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,700,1,200" />
  <link rel="stylesheet"
    href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,700,1,200" />
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  <!---------------------------------------------font-awesome--------------------------------------->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <script src="https://kit.fontawesome.com/99c47b3908.js" crossorigin="anonymous"></script>

  <!-----------------------------------------------bootstrap 5.2------------------------------------------>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
    crossorigin="anonymous"></script>


  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
    integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
    crossorigin="anonymous"></script>
    
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js"
    integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V"
    crossorigin="anonymous"></script>
  <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicon11.png' %}">
  <link rel="apple-touch-icon" href="{% static 'images/favicon11.png' %}">
  <link rel="apple-touch-icon" sizes="72x72" href="{% static 'images/favicon11.png' %}">
  <link rel="apple-touch-icon" sizes="114x114" href="{% static 'images/favicon11.png' %}">
  <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/favicon11.png' %}">
  <link rel="apple-touch-icon" sizes="228x228" href="{% static 'images/favicon11.png' %}">
  <title>DarkWear</title>
  <style>

  </style>
</head>

<body>

  <!-----------------------------------------------------navbar---------------------------------------------------------->

  <nav class="navbar navbar-expand-lg navbar-light bg-white p-3">
    <div class="container-fluid bg">
      <a class="navbar-brand logo1" href="#">DarkWear</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class=" collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ms-auto ">
          <li class="nav-item">
            <a class="nav-link mx-2" aria-current="page" href="{% url 'homepage:home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link mx-2" href="#">Sales</a>
          </li>
          <li class="nav-item">
            <a class="nav-link mx-2" href="{% url 'homepage:jacket' %}">Jackets</a>
          </li>
          <li class="nav-item">
            <a class="nav-link mx-2" href="{% url 'homepage:hoodie' %}">Hoodies</a>
          </li>
          <li class="nav-item">
            <a class="nav-link mx-2" href="{% url 'homepage:sweater' %}">Sweaters</a>
          </li>
          <li class="nav-item">
            <a class="nav-link mx-2" href="{% url 'homepage:t-shirt' %}">T-Shirts</a>
          </li>
          <li class="nav-item">
            <a class="nav-link mx-2" href="{% url 'homepage:pants' %}">Pants</a>
          </li>
          <li class="nav-item">
            <a class="nav-link mx-2" href="{% url 'homepage:hats' %}">Hats</a>
          </li>
          <li class="nav-item">
            <a class="nav-link mx-2" href="{% url 'homepage:accessories' %}">Accessories</a>
          </li>
        </ul>

        <ul class="navbar-nav ms-auto d-none d-lg-inline-flex">
          <li class="nav-item mx-1">
            <a class="nav-link text-dark h5" href="" target="blank">
              <span class="material-symbols-outlined">
                <!-- search -->
            </span>
            </a>
          </li>
          <li class="nav-item mx-1">
            <a class="nav-link text-dark h5" href="" target="blank">
              <span class="material-symbols-outlined">
                <!-- person -->
              </span>
            </a>
          </li>
          <li class="nav-item mx-1">
            <a class="nav-link text-dark h5" href="" target="blank">
              <span class="material-symbols-outlined">
                <!-- shopping_cart -->
              </span>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <!-----------------------------------------------------navbar---------------------------------------------------------->

  <!-----------------------------------------------------main1---------------------------------------------------------->
  
<div class="container ">
  <div class="row justify-content-center">
    <div class="col-md-10">
      {% for msg in messages %}
      <div class="alert alert-success justify-content-center align-items-center text-center" role="alert">
        {{msg}}
      </div>
      {% endfor %}
    </div>
  </div>
  
  <div class="row justify-content-center lofform">
    <div class="col-lg-6 col-md-12 col-sm-12 col-xs-12 justify-content-center">
    <!-- Pills navs -->
        <ul class="nav nav-pills nav-justified mb-3" id="ex1" role="tablist">
          <li class="nav-item" role="presentation">
            <a class="nav-link active" id="tab-login" data-mdb-toggle="pill" href="{% url 'homepage:login' %}" role="tab"
              aria-controls="pills-login" aria-selected="false">Login</a>
          </li>
          <li class="nav-item" role="presentation">
            <a class="nav-link" id="tab-register" data-mdb-toggle="pill" href="{% url 'homepage:register' %}" role="tab"
              aria-controls="pills-register" aria-selected="true">Register</a>
          </li>
        </ul>
        <!-- Pills navs -->

                    <!-- Pills content -->
          <div class="tab-content">
            <div class="tab-pane fade show active"  role="tabpanel" aria-labelledby="tab-login">
              <form id="pills-login"  method="POST" name="login" enctype="multipart/form-data">
                {% csrf_token %}
                <!-- Email input -->
                <div class="form-outline mb-4">
                  <input type="email" id="loginName" class="form-control" name="email">
                  <label class="form-label" for="loginName">Email</label>
                </div>

                <!-- Password input -->
                <div class="form-outline mb-4">
                  <input type="password" id="loginPassword" class="form-control" name="password">
                  <label class="form-label" for="loginPassword">Password</label>
                </div>

                <!-- 2 column grid layout -->
                <div class="row mb-4 justify-content-around">
                  <div class="col-md-6 d-flex">
                    <!-- Checkbox -->
                    <div class="form-check mb-3 mb-md-0">
                      <input class="form-check-input" type="checkbox" value="" id="loginCheck" checked />
                      <label class="form-check-label" for="loginCheck"> Remember me </label>
                    </div>
                  </div>

                  <div class="col-md-6 d-flex">
                    <!-- Simple link -->
                    <a href="#!">Forgot password?</a>
                  </div>
                </div>
                {{message}}<br>


                <!-- Submit button -->
                <button type="submit" class="btn btn-primary btn-block mb-4">Log in</button>

                <!-- Register buttons -->
                <div class="text-center">
                  <p>Not a member? <a href="{% url 'homepage:register' %}">Register</a></p>
                </div>
              </form>
            </div>
            
          </div>
</div>
</div>
<!-- Pills content -->
</div>
    <!------------------------------------------------------footer----------------------------------------------------->


    <!-- Remove the container if you want to extend the Footer to full width. -->
<div class="container-fluid"  style="background-color: black;">
  <!-- Footer -->
  <footer class="text-center text-lg-start text-white" style="background-color: #0000; z-index: 35;">
    <!-- Grid container -->
    <div class="container p-4 pb-0">
      <!-- Section: Links -->
      <section class="">
        <!--Grid row-->
        <div class="row">
          <!-- Grid column -->
          <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3">
            <h3 class="mb-4 font-weight-bold" style="font-family: impact;">
              <i>DarkWear</i>
            </h3>
            <p>
              We believe that wearing clothing that fits<br>
               your inner expression empowers you.
            </p>
          </div>
          <!-- Grid column -->

          <hr class="w-100 clearfix d-md-none" />

          <!-- Grid column -->
          <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mt-3">
            <h6 class="text-uppercase mb-4 font-weight-bold">Communities</h6>
            <p>
              <a class="text-white"style="text-decoration: none;" >Techwear</a>
            </p>
            <p>
              <a class="text-white" style="text-decoration: none;">NikeTech</a>
            </p>
            <p>
              <a class="text-white" style="text-decoration: none;">StreetWear</a>
            </p>
          </div>
          <!-- Grid column -->

          <hr class="w-100 clearfix d-md-none" />

          <!-- Grid column -->
          <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mt-3">
            <h6 class="text-uppercase mb-4 font-weight-bold">
              Useful links
            </h6>
            <p>
              <a class="text-white" style="text-decoration: none;">Your Account</a>
            </p>
            <p>
              <a class="text-white" style="text-decoration: none;">your Orders</a>
            </p>
            <p>
              <a class="text-white" style="text-decoration: none;">Track Order</a>
            </p>
            <p>
              <a class="text-white" style="text-decoration: none;">Help</a>
            </p>
          </div>

          <!-- Grid column -->
          <hr class="w-100 clearfix d-md-none" />

          <!-- Grid column -->
          <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mt-3">
            <h6 class="text-uppercase mb-4 font-weight-bold">Contact</h6>
            <p><i class="fas fa-home mr-3"></i> New York, NY 10012, US</p>
            <p><i class="fas fa-envelope mr-3"></i> info@gmail.com</p>
            <p><i class="fas fa-phone mr-3"></i> + 01 234 567 88</p>
            <p><i class="fas fa-print mr-3"></i> + 01 234 567 89</p>
          </div>
          <!-- Grid column -->
        </div>
        <!--Grid row-->
      </section>
      <!-- Section: Links -->

      <hr class="my-3">

      <!-- Section: Copyright -->
      <section class="p-3 pt-0">
        <div class="row d-flex align-items-center">
          <!-- Grid column -->
          <div class="col-md-7 col-lg-8 text-center text-md-start">
            <!-- Copyright -->
            <div class="p-3">
              © 2022 Copyright:
              <a class="text-white" style="text-decoration: none;" href="#">darkwear.com</a>
            </div>
            <!-- Copyright -->
          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-5 col-lg-4 ml-lg-0 text-center text-md-end">
            <!-- Facebook -->
            <a
               class="btn btn-outline-light btn-floating m-1"
               class="text-white"
               role="button"
               ><i class="fab fa-facebook-f"></i
              ></a>

            <!-- Twitter -->
            <a
               class="btn btn-outline-light btn-floating m-1"
               class="text-white"
               role="button"
               ><i class="fab fa-twitter"></i
              ></a>

            <!-- Google -->
            <a
               class="btn btn-outline-light btn-floating m-1"
               class="text-white"
               role="button"
               ><i class="fab fa-google"></i
              ></a>

            <!-- Instagram -->
            <a
               class="btn btn-outline-light btn-floating m-1"
               class="text-white"
               role="button"
               ><i class="fab fa-instagram"></i
              ></a>
          </div>
          <!-- Grid column -->
        </div>
      </section>
      <!-- Section: Copyright -->
    </div>
    <!-- Grid container -->
  </footer>
  <!-- Footer -->
</div>
  </body>
</html>

home/templates/home_templates/sam.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet"
    href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,700,0,200" />
  <link rel="stylesheet"
    href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,700,1,200" />
  <link rel="stylesheet"
    href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,700,1,200" />
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <script src="https://kit.fontawesome.com/99c47b3908.js" crossorigin="anonymous"></script>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"
    integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js"
    integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V"
    crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="//https://cdnjs.cloudflare.com/ajax/libs/gsap/3.6.1/gsap.min.js"></script>

    <script src="//https://cdnjs.cloudflare.com/ajax/libs/zepto/1.2.0/zepto.min.js"></script>
  
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <style>
        .product-grid{
    font-family: 'Poppins', sans-serif;
    text-align: center;
}
.product-grid .product-image{
    overflow: hidden;
    position: relative;
    z-index: 1;
}
.product-grid .product-image a.image{display: block; }
.product-grid .product-image img{
    width: 100%;
    height: auto;
}
.product-grid .product-discount-label{
    color: #fff;
    background: #A5BA8D;
    font-size: 13px;
    font-weight: 600;
    line-height: 25px;
    padding: 0 20px;
    position: absolute;
    top: 10px;
    left: 0;
}
.product-grid .product-links{
    padding: 0;
    margin: 0;
    list-style: none;
    position: absolute;
    top: 10px;
    right: -50px;
    transition: all .5s ease 0s;
}
.product-grid:hover .product-links{ right: 10px; }
.product-grid .product-links li a{
    color: #333;
    background: transparent;
    font-size: 17px;
    line-height: 38px;
    width: 38px;
    height: 38px;
    border: 1px solid #333;
    border-bottom: none;
    display: block;
    transition: all 0.3s;
}
.product-grid .product-links li:last-child a{ border-bottom: 1px solid #333; }
.product-grid .product-links li a:hover{
    color: #fff;
    background: #333;
}
.product-grid .add-to-cart{
    background: #A5BA8D;
    color: #fff;
    font-size: 16px;
    text-transform: uppercase;
    letter-spacing: 2px;
    width: 100%;
    padding: 10px 26px;
    position: absolute;
    left: 0;
    bottom: -60px;
    transition: all 0.3s ease 0s;
}
.product-grid:hover .add-to-cart{ bottom: 0; }
.product-grid .add-to-cart:hover{ text-shadow: 4px 4px rgba(0,0,0,0.2); }
.product-grid .product-content{
    background: #fff;
    padding: 15px;
    box-shadow: 0 0 0 5px rgba(0,0,0,0.1) inset;
}
.product-grid .title{
    font-size: 16px;
    font-weight: 600;
    text-transform: capitalize;
    margin: 0 0 7px;
}
.product-grid .title a{
    color: #777;
    transition: all 0.3s ease 0s;
}
.product-grid .title a:hover{ color: #a5ba8d; }
.product-grid .price{
    color: #0d0d0d;
    font-size: 14px;
    font-weight: 600;
}
.product-grid .price span{
    color: #888;
    font-size: 13px;
    font-weight: 400;
    text-decoration: line-through;
}
@media screen and (max-width: 990px){
    .product-grid{ margin-bottom: 30px; }
}

    </style>
</head>
<body>

    <div class="offcanvas offcanvas-start w-25" tabindex="-1" id="offcanvas" data-bs-keyboard="false" data-bs-backdrop="false">
        <div class="offcanvas-header">
            <h6 class="offcanvas-title d-none d-sm-block" id="offcanvas">Menu</h6>
            <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body px-0">
            <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-start" id="menu">
                <li class="nav-item">
                    <a href="#" class="nav-link text-truncate">
                        <i class="fs-5 bi-house"></i><span class="ms-1 d-none d-sm-inline">Home</span>
                    </a>
                </li>
                <li>
                    <a href="#submenu1" data-bs-toggle="collapse" class="nav-link text-truncate">
                        <i class="fs-5 bi-speedometer2"></i><span class="ms-1 d-none d-sm-inline">Dashboard</span> </a>
                </li>
                <li>
                    <a href="#" class="nav-link text-truncate">
                        <i class="fs-5 bi-table"></i><span class="ms-1 d-none d-sm-inline">Orders</span></a>
                </li>
                <li class="dropdown">
                    <a href="#" class="nav-link dropdown-toggle  text-truncate" id="dropdown" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fs-5 bi-bootstrap"></i><span class="ms-1 d-none d-sm-inline">Bootstrap</span>
                    </a>
                    <ul class="dropdown-menu text-small shadow" aria-labelledby="dropdown">
                        <li><a class="dropdown-item" href="#">New project...</a></li>
                        <li><a class="dropdown-item" href="#">Settings</a></li>
                        <li><a class="dropdown-item" href="#">Profile</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Sign out</a></li>
                    </ul>
                </li>
                <li>
                    <a href="#" class="nav-link text-truncate">
                        <i class="fs-5 bi-grid"></i><span class="ms-1 d-none d-sm-inline">Products</span></a>
                </li>
                <li>
                    <a href="#" class="nav-link text-truncate">
                        <i class="fs-5 bi-people"></i><span class="ms-1 d-none d-sm-inline">Customers</span> </a>
                </li>
            </ul>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col min-vh-100 py-3">
                <!-- toggler -->
                <button class="btn float-end" data-bs-toggle="offcanvas" data-bs-target="#offcanvas" role="button">
                    <i class="bi bi-arrow-right-square-fill fs-3" data-bs-toggle="offcanvas" data-bs-target="#offcanvas"></i>
                </button>
                Content..
            </div>
        </div>
    </div>
    

</body>
</html>