darkwear/urls.py
from django.conf import settings 
from django.urls import path,include
from django.contrib import admin 
from django.conf.urls.static import static
urlpatterns = [
    path('adminww/', admin.site.urls),
    path('',include("home.urls")),
    path('user/',include("user.urls")),
    path('seller/',include("seller.urls")),
    path('admin/',include("dw_admin.urls")),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name='homepage'
urlpatterns = [
    path('',views.home_homepage,name = 'home'),
    path('seller_login',views.seller_login,name = 'seller_login'),
    path('seller_registration',views.seller_registration,name = 'seller_registration'),
    path('login',views.home_login,name = 'login'),
    path('register',views.home_register,name = 'register'),
    path('jacket',views.home_jacket,name = 'jacket'),
    path('hoodie',views.home_hoodie,name = 'hoodie'),
    path('sweater',views.home_sweater,name = 'sweater'),
    path('t-shirt',views.home_tshirt,name = 't-shirt'),
    path('pants',views.home_pant,name = 'pants'),
    path('hats',views.home_hats,name = 'hats'),
    path('jewelery',views.home_jewelery,name = 'jewelery'),
    path('accessories',views.home_accessories,name = 'accessories'),
    path('product_details',views.product_details,name = 'product_details')

]

seller/urls.py
from django.urls import path
from . import views


app_name='seller'
urlpatterns = [
    path('',views.seller_home,name = 'shome'),
    path('viewproducts',views.seller_products,name = 'viewproducts'),
    path('btn_approve_product/<int:pid>',views.btn_approve_product,name='btn_approve_product'),
    path('btn_reject_product/<int:pid>',views.btn_reject_product,name='btn_reject_product'),
    path('view_details/<int:pid>',views.view_details,name = 'view_details'),
    path('view_approved_products',views.seller_approved_products,name = 'view_approved_products'),
    path('product_variant',views.seller_variant,name = 'variant'),
    path('view_variant/<int:pid>',views.view_variant,name = 'view_variant'),
    path('delete_product/<int:pid>',views.delete_product,name = 'delete_product'),
    path('product_list',views.product_list, name='product_list'),
    path('changepassword',views.seller_change_password,name = 'changepassword'),
    path('stockupdate',views.seller_update_stock,name = 'stockupdate'),
    path('get_product_name/', views.get_product_name, name='get_product_name'),
    path('get_variant/',views.get_variant, name = 'get_variant'),
    path('get_size/',views.get_size,name = 'get_size'),
    path('stock_up',views.seller_stock_up,name = 'stock_up'),
    path('add_stock',views.seller_add_stock,name = 'add_stock'),
    path('profile',views.seller_profile,name = 'profile'),
    path('edit_approved_products/<int:pid>',views.edit_approved_products,name = "edit_approved_products")
]           

user/urls.py
from django.urls import path
from . import views
app_name='user'
urlpatterns = [
    path('',views.user,name='home'),
    path('jacket',views.user_jacket,name = 'jacket'),
    path('hoodie',views.user_hoodie,name = 'hoodie'),
    path('sweater',views.user_sweater,name = 'sweater'),
    path('t-shirt',views.user_tshirt,name = 't-shirt'),
    path('pants',views.user_pant,name = 'pants'),
    path('hats',views.user_hats,name = 'hats'),
    path('accessories',views.user_accessories,name = 'accessories'),
    path('product_details/<int:p_id>',views.user_product_details,name = 'product_details'),
    path('get_quantity/',views.get_quantity, name='get_quantity'),
    # path('profile',views.profile,name = 'profile'),
    path('personal_details',views.personal_details, name = 'personal_details'),
    path('edit_personal_details',views.edit_personal_details,name = 'edit_personal_details'),
    path('manage_address',views.manage_address, name = 'manage_address'),
    path('edit_manage_address',views.edit_manage_address, name = 'edit_manage_address'),
    path('coupon',views.my_coupons, name = 'coupon'),
    path('my_reviews',views.my_reviews,name = 'my_reviews'),
    path('cart',views.user_cart,name = 'cart'),
    path('update_cart/', views.update_cart, name='update_cart'),
    path('delete_from_cart/', views.delete_from_cart, name='delete_from_cart'),
    # path('checkout',views.checkout, name = 'checkout'),
    path('pdf',views.generate_pdf, name = 'pdf'),
    
]

seller/models.py
from django.db import models
from unittest.util import _MAX_LENGTH
from home.models import Seller
from home.models import Customer

# Create your models here.
class Products(models.Model):
    product_name = models.CharField(max_length=60)
    description = models.CharField(max_length=300)
    thumbnail = models.ImageField(upload_to='products/')
    size_guide = models.ImageField(upload_to='products/',null=True,blank=True)
    material_id = models.ForeignKey("Material", on_delete=models.CASCADE) 
    category_id = models.ForeignKey("Category", on_delete=models.CASCADE)
    fit_id = models.ForeignKey("Fit",on_delete=models.CASCADE,null=True,blank=True) 
    pattern_id = models.ForeignKey("Pattern",on_delete=models.CASCADE,null=True,blank=True)
    sleeve_id = models.ForeignKey("Sleeve",on_delete=models.CASCADE, null=True, blank=True)
    neck_id = models.ForeignKey("Neck",on_delete=models.CASCADE,null=True, blank=True)  
    price = models.BigIntegerField()
    seller_id = models.ForeignKey("home.Seller",on_delete=models.CASCADE,null=True)
    status = models.CharField(max_length=20,default='pending')
    
class Album(models.Model):
    image =models.ImageField(upload_to='products/')
    product = models.ForeignKey("Products",on_delete=models.CASCADE)
    
class Category(models.Model):
    category_name = models.CharField(max_length=80)    
    
class Size(models.Model):
    size = models.CharField(max_length=50)  
    
class Material(models.Model):
    material = models.CharField(max_length=80)     
    
class Fit(models.Model):
    fit_type = models.CharField(max_length=100)     
    
class Pattern(models.Model):
    pattern = models.CharField(max_length=100) 
    
class Sleeve(models.Model):
    sleeve_type = models.CharField(max_length=130)    
    
class Neck(models.Model):
    neck_type = models.CharField(max_length=100)    
    
class Variant(models.Model):
    product_id = models.ForeignKey("Products", on_delete=models.CASCADE) 
    size_id = models.ForeignKey("Size", on_delete=models.CASCADE) 
    quantity = models.BigIntegerField()
        

seller/forms.py
# from django import forms
# from .models import Products

# class ProductForm(forms.ModelForm):
#     class Meta:
#         model = Products
#         fields = '__all__'

#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         if 'category' in self.data and self.data['category'] == 'accessories':
#             # exclude the fields you don't want to show
#             self.fields.pop('sleeve', None)
#             self.fields.pop('fit', None)
#             self.fields.pop('neck', None)

seller/views.py
from django.http import Http404, HttpResponseBadRequest, JsonResponse, HttpRequest
from django.shortcuts import get_object_or_404, render,redirect
from .models import Category,Fit,Material,Pattern,Neck,Sleeve,Size,Variant,Products,Album
from home.models import Seller
from user.models import Cart
import pprint
import os
from django.contrib import messages




# Create your views here.
def seller_variant(request):
    if request.method == "POST":
        product_id = request.POST.get("product_id")
        quantities = request.POST.getlist("quantity[]")
        sizes = request.POST.getlist("size_id[]")
        print(product_id)
        print(quantities)

        for i in range(len(quantities)):
            variant = Variant(
                product_id_id=product_id,
                size_id_id=sizes[i],
                quantity=quantities[i]
            )
            variant.save()

        return redirect("seller:variant")
    products = Products.objects.all()
    size = Size.objects.all()
    return render(request,'seller_templates/add_product_variant.html',{'products':products,'sizes':size})

def view_variant(request,pid=0):
    variant = Variant.objects.filter(product_id = pid)
    return render(request,'seller_templates/view_variants.html',{'data':variant})

def product_list(request):
    products = Products.objects.all().values('id', 'product_name')
    return JsonResponse(list(products), safe=False)

def delete_product(request,pid=0):
    product = Products.objects.get(id = pid)
    if len(product.thumbnail)>0:
        os.remove(product.thumbnail.path) 
    product.delete()
    messages.success(request,"Product deleted successfully")
    return redirect("seller:viewproducts")
    return render(request,'seller_templates/seller_view.html')

def seller_home(request):
    sellers = Seller.objects.get(id = request.session['seller'])
    category = Category.objects.all()
    fit = Fit.objects.all()
    material = Material.objects.all()
    neck = Neck.objects.all()
    sleeve = Sleeve.objects.all()
    pattern = Pattern.objects.all()
    
    if request.method == 'POST':
        p_name = request.POST['productname']
        p_description = request.POST['description']
        p_category = Category.objects.get(id = request.POST['category'])
        p_price = request.POST['price']
        p_image = request.FILES['pic']
        p_album = request.FILES.getlist('files[]')
        seller = Seller.objects.get(id = request.session['seller'])
        p_material = Material.objects.get(id = request.POST['material'])
        if p_category.category_name in ["t-shirt", "jacket", "sweatshirt", "hoodie"]:
            p_fit = Fit.objects.get(id = request.POST['fittype'])
            p_sleeve = Sleeve.objects.get(id = request.POST['sleeve'])
            p_neck = Neck.objects.get(id = request.POST['neck'])
            p_pattern = Pattern.objects.get(id = request.POST['pattern'])
            p_size_guide = request.FILES['size_guide']
        elif  p_category.category_name == "pant":
            p_fit = Fit.objects.get(id = request.POST['fittype'])
            p_size_guide = request.FILES['size_guide']   
            p_sleeve = None
            p_neck = None
            p_pattern = None 
        else:
            p_fit = None
            p_sleeve = None
            p_neck = None
            p_pattern = None
            p_size_guide = None
             
        p_product = Products(
            product_name= p_name,
            description=  p_description,
            category_id = p_category,
            price= p_price,
            thumbnail =  p_image,
            size_guide = p_size_guide,
            seller_id = seller,
            material_id = p_material,
            fit_id = p_fit,
            sleeve_id = p_sleeve,
            neck_id = p_neck,
            pattern_id = p_pattern
        )
        pprint.pprint(p_product)
        p_product.save()  
        product_id = p_product.id
        
        for i in p_album:
            album_p = Album(
                product_id = product_id,
                image = i 
            )
            album_p.save()
        
        
    context = {
        'categorys':category,
        'fits':fit,
        'materials':material,
        'necks':neck,
        'sleeves':sleeve,
        'patterns':pattern,
        'seller':sellers,
    }
    return render(request,'seller_templates/seller_index.html',context)

def seller_products(request):
    product_obj = Products.objects.filter(seller_id=request.session['seller'],status = 'pending')
    return render(request,'seller_templates/seller_view.html',{'data':product_obj})

def btn_approve_product(request,pid):
    product = Products.objects.filter(id = pid).update(status='approved')
    return redirect('seller:viewproducts')

def btn_reject_product(request,pid):
    product = Products.objects.filter(id = pid,status='pending').delete()
    return redirect('seller:viewproducts')

def view_details(request,pid):
    msg="" 
    product = Products.objects.get(id = pid)
    variants = Variant.objects.filter(product_id = pid)
    print(variants)
    album = Album.objects.filter(product_id = pid)
    
    show_fit_type = True
    show_size_guide = True
    if product.category_id.category_name in ['accessories', 'hat']:
        show_fit_type = False
        try:
            context = {
                'product': product,
                'variants': variants,
                'albums': album,
                'show_fit_type': show_fit_type,
                'show_size_guide': show_size_guide,
                'size_guide': product.size_guide.url
            }
        except ValueError:
            show_size_guide = False
            context = {
                'product': product,
                'variants': variants,
                'albums': album,
                'show_fit_type': show_fit_type,
                'show_size_guide': show_size_guide,
                'size_guide': None  # default value for size_guide
            }

    else:
        context = {
            'product': product,
            'variants': variants,
            'albums': album,
            'show_fit_type': show_fit_type,
            'show_size_guide': show_size_guide,
            'size_guide': product.size_guide.url
        }
        
    if request.method == 'POST':
        u_id=request.session.get('customer')
        quantity = request.POST.get('quantity')
        # v_id = request.POST.get('variant_id')
        # print(v_id)
        size = request.POST.get('size')
        size_id = size_id = int(size.split()[2].strip("()"))
        print(size_id)
        variants = Variant.objects.get(product_id = product,size_id=size_id)
        print(variants)
        item = Cart.objects.filter(customer_id =u_id ,product_id = pid,variant_id=variants.id).exists()
        print(item)
        if not item:           #same as if item == false:
            cart= Cart(customer_id =u_id,product_id = pid,variant_id=variants.id,qty = quantity)
            cart.save()
            return redirect('user:cart')

        else:
            print('already in cart')
            msg = 'Item already in cart'
    return render(request,'seller_templates/view_details.html',context)

def seller_approved_products(request):
    product_obj = Products.objects.filter(seller_id=request.session['seller'],status = 'approved')
    return render(request,'seller_templates/seller_approved_products.html',{'data':product_obj})
    
def seller_change_password(request):
    msg = ''
    if request.method == 'POST':
        old_pass = request.POST['old']
        new_pass = request.POST['confirm']
        try:
            seller_obj = Seller.objects.get(id = request.session['seller'],password = old_pass)
            Seller.objects.filter(id = request.session['seller']).update(password = new_pass)
            msg = 'Change Successfull'
            return render(request,'seller_templates/change_password.html',{'message1':msg})
        except:
            msg = 'old Password does not match' 
            return render(request,'seller_templates/change_password.html',{'message':msg})
    return render(request,'seller_templates/change_password.html')


def seller_update_stock(request):
    product = Products.objects.filter(seller_id=request.session['seller'])
    context = {
        'product':product
    }
    return render(request,'seller_templates/stock_update.html',context)

def get_product_name(request):
    product_id = request.GET.get('product_id')
    try:
        product = Products.objects.get(id=product_id)
        product_name = product.product_name
    except Products.DoesNotExist:
        raise Http404("Product does not exist")
    data = {
        'product_name': product_name,
    }
    return JsonResponse(data)

def get_variant(request):
    product_id = request.GET.get('product_id')
    try:
        variant_qs = Variant.objects.filter(product_id=product_id)
        variant_list = list(variant_qs.values())  # Convert the queryset to a list of dictionaries
    except Products.DoesNotExist:
        raise Http404("Product does not exist")
    data = {
        'variant': variant_list,
    }
    return JsonResponse(data)



def get_size(request: HttpRequest):
    if request.method == 'GET' and request.is_ajax():
        size_id = request.GET.get('size_id')
        size = Size.objects.filter(id=size_id).first()
        if size:
            size_name = size.size
            return JsonResponse({'size': size_name})
        else:
            return JsonResponse({'error': 'Size not found'})
    else:
        return HttpResponseBadRequest()
            
def edit_approved_products(request,pid):
    return render(request,'seller_templates/edit_approved_products.html')            

def seller_stock_up(request):
    id = request.POST['pno']
    prod = Products.objects.filter(id = id).values('product_name','Stock')
    protitle = prod[0]['product_name']
    prostock = prod[0]['Stock']
    print(protitle)
    context = {
        'product_name':protitle,

seller/templates/seller_templates/change_password.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Dashboard</title>

    <!-- Custom fonts for this template-->
    <!-- <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css"> -->
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.css' %}" rel="stylesheet">

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3"style="font-family: impact;"><i>DarkWear</i></div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" href="#">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Actions
            </div>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="{% url 'seller:shome' %}" data-toggle="collapse" data-target="#collapseTwo"
                    aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fas fa-fw fa-cog"></i>
                    <span>Add Products</span>
                </a>
                
            </li>

            <!-- Nav Item - Utilities Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="{% url 'seller:viewproducts' %}" data-toggle="collapse" data-target="#collapseUtilities"
                    aria-expanded="true" aria-controls="collapseUtilities">
                    <i class="fas fa-fw fa-wrench"></i>
                    <span>View Products</span>
                </a>

            </li>

            <li class="nav-item">
                <a class="nav-link collapsed" href="{% url 'seller:stockupdate' %}" data-toggle="collapse" data-target="#collapseUtilities"
                    aria-expanded="true" aria-controls="collapseUtilities">
                    <i class="fas fa-fw fa-wrench"></i>
                    <span>Update Stock</span>
                </a>

            </li>

            <li class="nav-item">
                <a class="nav-link collapsed" href="{% url 'seller:changepassword' %}" data-toggle="collapse" data-target="#collapseUtilities"
                    aria-expanded="true" aria-controls="collapseUtilities">
                    <i class="fas fa-fw fa-wrench"></i>
                    <span>Change Password</span>
                </a>

            </li>



            <!-- Nav Item - Charts -->
            <li class="nav-item">
                <a class="nav-link" href="charts.html">
                    <i class="fas fa-fw fa-chart-area"></i>
                    <span>Charts</span></a>
            </li>





        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Search -->
                    <form
                        class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                        <div class="input-group">
                            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                                aria-label="Search" aria-describedby="basic-addon2">
                            <div class="input-group-append">
                                <button class="btn btn-primary" type="button">
                                    <i class="fas fa-search fa-sm"></i>
                                </button>
                            </div>
                        </div>
                    </form>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                        <li class="nav-item dropdown no-arrow d-sm-none">
                            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-search fa-fw"></i>
                            </a>


                            <div class="topbar-divider d-none d-sm-block"></div>

                            <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="{% url 'seller:profile' %}" id="userDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">Account</span>
                                <!-- <img class="img-profile rounded-circle"
                                    src="img/undraw_profile.svg"> -->
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Profile
                                </a>
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Settings
                                </a>
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Activity Log
                                </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Logout
                                </a>
                            </div>
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        <h1 class="h3 mb-0 text-gray-800">Welcome Seller</h1>
                    </div>

                    <!-- Content Row -->



                    <!-- Content Row -->

                    <div class="row">

                        <!-- Area Chart -->
                        <div class="col-xl-8 col-lg-7">
                            <div class="card shadow mb-4">
                                <!-- Card Header - Dropdown -->
                                <div class="card-header py-3 align-items-center justify-content-between">
                                    <h6 class="m-0 font-weight-bold text-primary">View Products</h6>
                                    <br>
                                    <form id="form1" name="form1" method="POST" action="" enctype="multipart/form-data" onsubmit="return validation()">
                                        {% csrf_token %}
                                        <br>
                                        <table>
                                            <tr>
                                                <td><label>Old Password<label></td>
                                                <td><input type="text" name="old"
                                                        class="form-control border-0 small"></td>
                                            </tr>
                                            <tr>
                                                <td></td>
                                            </tr>
                                            <tr>
                                                <td><label>New Password<label></td>
                                                <td><input type="text" name="new" id="old"
                                                        class="form-control border-0 small"></td>
                                            </tr>
                                            <tr>
                                                <td></td>
                                            </tr>
                                            <tr>
                                                <td><label>Confirm Password<label></td>
                                                <td><input type="password" name="confirm" id="new"
                                                        class="form-control border-0 small"></td>
                                            </tr>
                                            <tr><td></td></tr>
                                            <tr align="center">
                                                <td></td>
                                                <td colspan="2"><button type="submit" 
                                                        class="btn btn-primary">submit</button></td>
                                            </tr>
                    
                                        </table>
                                    </form>
                                    <br><br>
                                    <span style="color: red;"><center>{{message}}</center></span>
                                    <span style="color: rgb(8, 245, 8);"><center>{{message1}}</center></span>
                                    <br><br>
                    

                                    
                                </div>

                            </div>
                        </div>


                    </div>

                    <!-- Content Row -->

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2021</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>

   


</body>

</html>

seller/templates/seller_templates/checkout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

seller/templates/seller_templates/edit_approved_products.html
{% extends 'seller_templates/index.html' %} {% load static %} {% block content %}
<link href="{% static 'css/sb-admin-2.css' %}" rel="stylesheet" />
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script> 


{% endblock %}  